name: Cache Keyman API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch from Keyman API
        run: sh download-latest.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Keyman API
