name: Cache Keyman API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Fetch from Keyman API
        run: make cache-responses
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Keyman API
          commit_author: "GitHub Actions <actions@github.com>"
